INSERT INTO requirements (name, type, is_global, min_age, gender) VALUES
('Развернутый анализ крови', 'lab', TRUE, NULL, NULL),
('Биохимический анализ крови (сахар, холестерин)', 'lab', TRUE, NULL, NULL),
('Общий анализ мочи', 'lab', TRUE, NULL, NULL),
('ЭКГ', 'instr', TRUE, NULL, NULL),
('Флюорография', 'instr', TRUE, NULL, NULL),
('Терапевт', 'exam', TRUE, NULL, NULL),
('Невролог', 'exam', TRUE, NULL, NULL),
('Психиатр', 'exam', TRUE, NULL, NULL),
('Нарколог', 'exam', TRUE, NULL, NULL),
('Гинеколог + мазок', 'exam', TRUE, NULL, 'female'),
('Маммография', 'instr', TRUE, '40', 'female'),
('Дерматовенеролог', 'exam', FALSE, NULL, NULL),
('Оториноларинголог', 'exam', FALSE, NULL, NULL),
('Аудиометрия', 'instr', FALSE, NULL, NULL),
('Исследование вестибулярного аппарата', 'instr', FALSE, NULL, NULL),
('Офтальмолог', 'exam', FALSE, NULL, NULL),
('Стоматолог', 'exam', FALSE, NULL, NULL),
('Хирург', 'exam', FALSE, NULL, NULL),
('Исследование уровня метгемоглобина в крови', 'lab', FALSE, NULL, NULL),
('Исследование уровня ретикулоцитов в крови', 'lab', FALSE, NULL, NULL),
('Исследование уровня карбоксигемоглобина в крови', 'lab', FALSE, NULL, NULL),
('Спирометрия', 'instr', FALSE, NULL, NULL),
('УЗИ органов брюшной полости', 'instr', FALSE, NULL, NULL),
('УЗИ органов малого таза', 'instr', FALSE, NULL, NULL),
('Исследование крови на RW', 'lab', FALSE, NULL, NULL),
('Мазок на гонорею', 'lab', FALSE, NULL, NULL),
('Исследование крови на брюшной тиф', 'lab', FALSE, NULL, NULL),
('Мазок на диз. группу', 'lab', FALSE, NULL, NULL),
('Кал на я/глистов', 'lab', FALSE, NULL, NULL),
('Мазок на стафилококк', 'lab', FALSE, NULL, NULL),
('ЭЭГ', 'instr', FALSE, NULL, NULL),
('ФГДС', 'instr', FALSE, NULL, NULL),
('Паллестезиметрия', 'instr', FALSE, NULL, NULL),
('УЗИ щитовидной железы', 'instr', FALSE, NULL, NULL),
('Биохимический анализ крови (ЩФ, о. билирубин, АЛТ, АСТ)', 'lab', FALSE, NULL, NULL),
('Анализ крови на HBs-Ag, анти-HBc-Ig (суммарные), анти-HCV-Ig (суммарные), ВИЧ', 'lab', FALSE, NULL, NULL),
('Рентгенография длинных трубчатых костей (фтор и его соединения)', 'instr', FALSE, NULL, NULL),
('Исследование уровня дельта аминолевулиновой кислоты или копропорфирина в моче', 'lab', FALSE, NULL, NULL);